_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
adjust_target:
    value: text
alpha:
    value: 1
batch_size:
    value: 1024
custom_template:
    value: false
data_location:
    value: /mlainas/bubble3jh/data/
dataset:
    value: ImageNet
group_coef:
    value: 0.75
half_prec:
    value: 0
ignore_wandb:
    value: false
model:
    value: ViT-B/32
model_location:
    value: ./checkpoints
negative_coef:
    value: 1.5
orthogonal_projection:
    value: naive
target_coef:
    value: 0.75
workers:
    value: 4
