_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "3":
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 1
batch_size:
    value: 1024
beta:
    value: 1
custom_template:
    value: class
data_location:
    value: /data1/bubble3jh/data/
dataset:
    value: ImageNet
method:
    value: text_svd_proj_mm
model:
    value: ViT-B/32
model_location:
    value: ./checkpoints
topk:
    value: 5
use_wandb:
    value: true
workers:
    value: 4
