_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
adjust_target:
    value: text
alpha:
    value: 1.5
batch_size:
    value: 1024
beta:
    value: 1
custom_template:
    value: false
data_location:
    value: /mlainas/bubble3jh/data/
dataset:
    value: ImageNet
gamma:
    value: 1
half_prec:
    value: 0
ignore_wandb:
    value: false
method:
    value: simple
model:
    value: ViT-B/32
model_location:
    value: ./checkpoints
topk:
    value: 5
workers:
    value: 4
